name: Node.js Package

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v3
        with:
          version: 'latest'
          runtime: 'node@lts'
      - run: pnpm build
      - run: pnpm publish --access public --no-git-checks
